const GAS_URL= "https://script.google.com/macros/s/AKfycbxEun0itM6WhbjiUej0fjsPITwop_ts89LOzqefkKfZrk8FrWQBc6qP6NmKFY_zWO83wg/exec";
function initAdminCopy(phoneSel='#adminPhone',btnSel='#copyAdminBtn'){try{const phone=document.querySelector(phoneSel);const btn=document.querySelector(btnSel);if(!phone||!btn)return;btn.addEventListener('click',async function(){await navigator.clipboard.writeText(phone.textContent.trim());btn.textContent='Copied';setTimeout(()=>btn.textContent='Copy',1200);});}catch(e){}}
function postToGAS(payload){return fetch(GAS_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).catch(e=>({status:'error',message:e.message}))}
function initSimForm(){const provider=document.getElementById('simProvider');const service=document.getElementById('simService');const desc=document.getElementById('simDescription');const total=document.getElementById('simTotal');const qty=document.getElementById('simQty');const phone=document.getElementById('simPhone');const txn=document.getElementById('simTxn');const submit=document.getElementById('simSubmit');provider.addEventListener('change',function(){populateSimServices(provider.value,service);service.dispatchEvent(new Event('change'))});service.addEventListener('change',function(){const val=service.value;desc.textContent=val?SERVICE_PRICES.sim[val].description:'Package details will appear here';calculateSimTotal();});qty.addEventListener('input',calculateSimTotal);function calculateSimTotal(){const val=service.value;if(!val){total.textContent='0';return}const price=SERVICE_PRICES.sim[val].price;total.textContent=(price*Number(qty.value||1)).toString()}submit.addEventListener('click',function(e){e.preventDefault();if(!provider.value||!service.value||!phone.value||!txn.value){showMessage('simMessage','Please fill all fields');return}const data={type:'sim',provider:provider.value,service:service.value,phone:phone.value,qty:Number(qty.value),total:Number(total.textContent),transaction:txn.value};showMessage('simMessage','Submitting...');postToGAS({action:'submitSimOrder',payload:data}).then(res=>{if(res.status==='success'){showMessage('simMessage','Order submitted successfully');document.getElementById('simForm').reset();total.textContent='0'}else showMessage('simMessage',res.message||'Submission failed')})})}
function populateSimServices(provider,selectEl){selectEl.innerHTML='<option value=\"\">Select Package</option>';if(provider==='mpt'){addOption(selectEl,'mpt-3gb',SERVICE_PRICES.sim['mpt-3gb'].name);addOption(selectEl,'mpt-5gb',SERVICE_PRICES.sim['mpt-5gb'].name)}if(provider==='telenor'){addOption(selectEl,'telenor-regular',SERVICE_PRICES.sim['telenor-regular'].name)}if(provider==='ooredoo'){addOption(selectEl,'ooredoo-basic',SERVICE_PRICES.sim['ooredoo-basic'].name)}}
function addOption(selectEl,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;selectEl.appendChild(o)}
function showMessage(id,msg){const el=document.getElementById(id);if(!el)return;el.textContent=msg}
function initGameForm(){const service=document.getElementById('gameService');const desc=document.getElementById('gameDescription');const total=document.getElementById('gameTotal');const qty=document.getElementById('gameQty');const phone=document.getElementById('gamePhone');const txn=document.getElementById('gameTxn');const submit=document.getElementById('gameSubmit');populateGameServices();service.addEventListener('change',function(){desc.textContent=service.value?SERVICE_PRICES.game[service.value].description:'Game details will appear here';calculateGameTotal()});qty.addEventListener('input',calculateGameTotal);function calculateGameTotal(){const val=service.value;if(!val){total.textContent='0';return}const price=SERVICE_PRICES.game[val].price;total.textContent=(price*Number(qty.value||1)).toString()}submit.addEventListener('click',function(e){e.preventDefault();if(!service.value||!phone.value||!txn.value){showMessage('gameMessage','Please fill all fields');return}const data={type:'game',service:service.value,target:phone.value,qty:Number(qty.value),total:Number(total.textContent),transaction:txn.value};showMessage('gameMessage','Submitting...');postToGAS({action:'submitGameOrder',payload:data}).then(res=>{if(res.status==='success'){showMessage('gameMessage','Order submitted successfully');document.getElementById('gameForm').reset();total.textContent='0'}else showMessage('gameMessage',res.message||'Submission failed')})})}
function populateGameServices(){const el=document.getElementById('gameService');el.innerHTML='<option value=\"\">Select Game TopUp</option>';Object.keys(SERVICE_PRICES.game).forEach(k=>addOption(el,k,SERVICE_PRICES.game[k].name))}
function initSmmForm(){const service=document.getElementById('smmService');const desc=document.getElementById('smmDescription');const priceEl=document.getElementById('smmPrice');const qty=document.getElementById('smmQty');const total=document.getElementById('smmTotal');const link=document.getElementById('smmLink');const txn=document.getElementById('smmTxn');const submit=document.getElementById('smmSubmit');populateSmmServices();service.addEventListener('change',function(){const v=service.value;if(v){desc.textContent=SERVICE_PRICES.smm[v].description;priceEl.textContent=SERVICE_PRICES.smm[v].price}else{desc.textContent='Service details will appear here';priceEl.textContent='0'}calculateSmmTotal()});qty.addEventListener('input',calculateSmmTotal);function calculateSmmTotal(){const v=service.value;if(!v){total.textContent='0';return}const unit=SERVICE_PRICES.smm[v].price;total.textContent=(unit*Number(qty.value||0)).toString()}submit.addEventListener('click',function(e){e.preventDefault();if(!service.value||!link.value||!qty.value||!txn.value){showMessage('smmMessage','Please fill all fields');return}const data={type:'smm',service:service.value,targetLink:link.value,qty:Number(qty.value),price:SERVICE_PRICES.smm[service.value].price,total:Number(document.getElementById('smmTotal').textContent),transaction:txn.value};showMessage('smmMessage','Submitting...');postToGAS({action:'submitSmmOrder',payload:data}).then(res=>{if(res.status==='success'){showMessage('smmMessage','Order submitted successfully');document.getElementById('smmForm').reset();document.getElementById('smmPrice').textContent='0';document.getElementById('smmTotal').textContent='0'}else showMessage('smmMessage',res.message||'Submission failed')})})}
function populateSmmServices(){const el=document.getElementById('smmService');el.innerHTML='<option value=\"\">Select SMM Service</option>';Object.keys(SERVICE_PRICES.smm).forEach(k=>addOption(el,k,SERVICE_PRICES.smm[k].name))}
function initP2PForm(){const amount=document.getElementById('p2pAmount');const from=document.getElementById('p2pFrom');const to=document.getElementById('p2pTo');const fee=document.getElementById('p2pFee');const receive=document.getElementById('p2pReceive');const txn=document.getElementById('p2pTxn');const submit=document.getElementById('p2pSubmit');function calculate(){const a=Number(amount.value||0);const f=Number((a*0.02).toFixed(2));fee.textContent=f;receive.textContent=(a-f).toString()}amount.addEventListener('input',calculate);from.addEventListener('change',validateMethods);to.addEventListener('change',validateMethods);function validateMethods(){if(from.value&&to.value&&from.value===to.value){showMessage('p2pMessage','From and To methods must be different');return false}showMessage('p2pMessage','');return true}submit.addEventListener('click',function(e){e.preventDefault();if(!amount.value||!from.value||!to.value||!txn.value){showMessage('p2pMessage','Please fill all fields');return}if(from.value===to.value){showMessage('p2pMessage','From and To methods must be different');return}const a=Number(amount.value);const f=Number((a*0.02).toFixed(2));const r=a-f;const data={type:'p2p',from:from.value,to:to.value,amount:a,fee:f,receive:r,transaction:txn.value};showMessage('p2pMessage','Submitting...');postToGAS({action:'submitP2POrder',payload:data}).then(res=>{if(res.status==='success'){showMessage('p2pMessage','Exchange submitted successfully');document.getElementById('p2pForm').reset();fee.textContent='0';receive.textContent='0'}else showMessage('p2pMessage',res.message||'Submission failed')})})}
function initStatusPage(){const searchBtn=document.getElementById('statusSearch');const input=document.getElementById('statusPhone');const results=document.getElementById('statusResults');searchBtn.addEventListener('click',function(){const q=input.value.trim();if(!q){results.innerHTML='<div class=\"status-card\">Please provide phone or transaction id</div>';return}results.innerHTML='<div class=\"status-card\">Searching...</div>';fetch(GAS_URL+'?action=getOrders&query='+encodeURIComponent(q)).then(r=>r.json()).then(res=>{if(res.status==='success'&&res.data&&res.data.length){results.innerHTML='';res.data.forEach(o=>{const el=document.createElement('div');el.className='status-card';el.innerHTML=`<div><strong>OrderID:</strong> ${o.OrderID||o.orderId||''}</div><div><strong>Category:</strong> ${o.Category||o.category||''}</div><div><strong>Service:</strong> ${o.Service||o.service||''}</div><div><strong>Target:</strong> ${o.Phone||o.Target||o.GameID||o.TargetLink||''}</div><div><strong>Total:</strong> ${o.Total||o.total||''}</div><div><strong>Status:</strong> ${o.Status||o.status||''}</div><div><strong>Timestamp:</strong> ${o.Timestamp||o.timestamp||''}</div>`;results.appendChild(el)})}else results.innerHTML='<div class=\"status-card\">No orders found</div>'}).catch(()=>results.innerHTML='<div class=\"status-card\">Error fetching orders</div>')})}
function renderServicesCatalog(){const container=document.getElementById('servicesCatalog');if(!container)return;container.innerHTML='';Object.keys(SERVICE_PRICES).forEach(cat=>{Object.keys(SERVICE_PRICES[cat]).forEach(key=>{const item=SERVICE_PRICES[cat][key];const card=document.createElement('div');card.className='catalog-item';card.innerHTML=`<div class=\"title\">${item.name}</div><div class=\"desc\">${item.description}</div><div class=\"price\">${item.price} Ks</div><div style=\"margin-top:10px\"><a class=\"btn\" href=\"${cat==='sim'?'order_sim.html':cat==='game'?'order_game.html':'order_smm.html'}\">Order</a></div>`;container.appendChild(card)})})}
function loadStats(){fetch(GAS_URL+'?action=getStats').then(r=>r.json()).then(res=>{if(res.status==='success'){document.getElementById('totalOrders').textContent=res.data.totalOrders||0;document.getElementById('revenue').textContent=(res.data.revenue||0)+' Ks';document.getElementById('pending').textContent=res.data.pending||0}}).catch(()=>{})}
async function submitOrder(payload) {
  try {
    const res = await fetch(GAS_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });

    const text = await res.text();
    alert("Response: " + text);
  } catch (err) {
    alert("Fetch Error: " + err.message);
  }
}
